name: tiktak
description: TikTok Clone App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.0
  http: ^1.2.0
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true
